### ISSUE TITLE
Navigating to "Team" throws an error

### ISSUE THREAD

**Issue by fcuringa** [TMEIT/website#190]
How to reproduce:

1. Click on "Team" in the top bar

I got this error:

```
Unhandled Thrown Error!
Failed to fetch
TypeError: Failed to fetch
    at l (https://tmeit.se/static/front/574-bundle-26e767cdcc9eabbcab34.js:1:8483)
    at Object.fetch (https://tmeit.se/static/front/574-bundle-26e767cdcc9eabbcab34.js:1:10742)
    at Object.get (https://tmeit.se/static/front/574-bundle-26e767cdcc9eabbcab34.js:1:10822)
    at loader (https://tmeit.se/static/front/main-d91a9049-bundle-b0dff3118a50ce3f0e4d.js:1:3524)
    at async G (https://tmeit.se/static/front/npm.remix-run-bundle-226a2db4f6d335e41bd5.js:2:22979)
    at async Promise.all (index 0)
    at async z (https://tmeit.se/static/front/npm.remix-run-bundle-226a2db4f6d335e41bd5.js:2:15104)
    at async https://tmeit.se/static/front/npm.remix-run-bundle-226a2db4f6d335e41bd5.js:2:14211
    at async W (https://tmeit.se/static/front/npm.remix-run-bundle-226a2db4f6d335e41bd5.js:2:13435)
    at async Object.navigate (https://tmeit.se/static/front/npm.remix-run-bundle-226a2db4f6d335e41bd5.js:2:17159)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own errorElement props on <Route>
```

Some missing static resource?

**Comment by JustinLex** [comment]
🥲 https://stackoverflow.com/questions/63511413/fastapi-redirection-for-trailing-slash-returns-non-ssl-link

**Comment by JustinLex** [comment]
Temp fix: #191

but we need to also fix the backend from sending these redirects
